### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by suresh-s** [huangchuchuan/SVM-LBP-picture-classifier#4]
I am getting following error,  Could you help me to resolve this issue

Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
Traceback (most recent call last):
  File "main.py", line 124, in <module>
    s = main()
  File "main.py", line 93, in main
    [1] * len(pos_file_path_list),
TypeError: object of type 'map' has no len()

**Comment by ZYY1015027303** [comment]
我也是从float64到uint8的有损转换。范围[0,1]。在保存之前将图像转换为uint8以抑制此警告。
但是文件
“main.py”，第124行，在
s = main（）
文件“main.py”，第93行，在main 
[1] * len（pos_file_path_list）中，
TypeError：类型对象'map'没有len（）
这个错误是python版本的问题。只需要list（map(~~~)）就可以了
